---
title: "Simulación ARMA y ACF Teórica"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Simulación y ACF

Vamos a simular un proceso $\{X_{t}\}\sim$ IID

```{r SimulIID}
n=200 #Tamaño de la serie
l=50 #condiciones iniciales
theta=-0.5 
phi=0.5
sigma=2
###Simulación IID####
serieIID=as.ts(rnorm(n,0,2))
plot(serieIID,main='IID')
acf(serieIID)
```

```{r MA1}
#####Simulación MA(1)#####
ruido=rnorm(n+l,0,sigma)
MA1aux=rep(0,n+l)
MA1aux
for(j in 2:(n+l))
{
  MA1aux[j]=theta*ruido[j-1]+ruido[j]
}
MA1=as.ts(MA1aux[l+1:n])
plot(MA1)
acf(MA1)
```


## Simulación de procesos ARMA


```{r ARMA, echo=FALSE}
Tlength=200
arimaej=arima.sim(list(order = c(1,0,1),ar = c(0.7),ma=c(0.6)), n = Tlength)
plot(arimaej,main='ARMA(1,1)')
acf(arimaej)
```

```{r ACFTeorica}
acf_ARMA<- ARMAacf(ar=c(0.7),ma=c(0.6), lag.max = 10)
lags <- 0:10 
plot(lags,acf_ARMA,xlim=c(1,10),ylab = "ACF",type="h",main = "ACF para ARMA(1,1)")
abline(h=0) #Agrega un eje al gráfico
```

```{r}
library(UnitCircle)
UnitCircle::uc.check(c(2,0,2.2,-3))
```

```{r}
#####Simulación IC n=30#####
set.seed(1)
theta <- -0.7
n<- 30
ruido30=rnorm(n,0,sigma)
MA1aux30=rep(0,n)
for(j in 2:n)
{
  MA1aux30[j]=theta*ruido30[j-1]+ruido30[j]
}
MA130=as.ts(MA1aux30[1:n])
nu <- NULL
for (h in 1:(8)) {
  g <- acf(MA130, lag.max = 9, plot=FALSE)
  nu[h] <- (1 - h/n)*g$acf[h]
}
n_30 <- c(mean(MA130) - qnorm(0.975)*(1/sqrt(n))*sqrt(sum(nu)),
          mean(MA130) + qnorm(0.975)*(1/sqrt(n))*sqrt(sum(nu)))
#####Simulación IC n=100#####
set.seed(1)
theta <- -0.7
n<- 100
ruido30=rnorm(n,0,sigma)
MA1aux30=rep(0,n)
for(j in 2:n)
{
  MA1aux30[j]=theta*ruido30[j-1]+ruido30[j]
}
MA130=as.ts(MA1aux30[1:n])
nu <- NULL
for (h in 1:(8)) {
  g <- acf(MA130, lag.max = 9, plot=FALSE)
  nu[h] <- (1 - h/n)*g$acf[h]
}
n_100 <- c(mean(MA130) - qnorm(0.975)*(1/sqrt(n))*sqrt(sum(nu)),
          mean(MA130) + qnorm(0.975)*(1/sqrt(n))*sqrt(sum(nu)))
#####Simulación IC n=500#####
set.seed(1)
theta <- -0.7
n<- 500
ruido30=rnorm(n,0,sigma)
MA1aux30=rep(0,n)
for(j in 2:n)
{
  MA1aux30[j]=theta*ruido30[j-1]+ruido30[j]
}
MA130=as.ts(MA1aux30[1:n])
nu <- NULL
for (h in 1:(8)) {
  g <- acf(MA130, lag.max = 9, plot=FALSE)
  nu[h] <- (1 - h/n)*g$acf[h]
}
n_500 <- c(mean(MA130) - qnorm(0.975)*(1/sqrt(n))*sqrt(sum(nu)),
          mean(MA130) + qnorm(0.975)*(1/sqrt(n))*sqrt(sum(nu)))
#####Simulación IC n=1000#####
set.seed(1)
theta <- -0.7
n<- 1000
ruido30=rnorm(n,0,sigma)
MA1aux30=rep(0,n)
for(j in 2:n)
{
  MA1aux30[j]=theta*ruido30[j-1]+ruido30[j]
}
MA130=as.ts(MA1aux30[1:n])
nu <- NULL
for (h in 1:(8)) {
  g <- acf(MA130, lag.max = 9, plot=FALSE)
  nu[h] <- (1 - h/n)*g$acf[h]
}
n_1000 <- c(mean(MA130) - qnorm(0.975)*(1/sqrt(n))*sqrt(sum(nu)),
          mean(MA130) + qnorm(0.975)*(1/sqrt(n))*sqrt(sum(nu)))

rbind(n_30, n_100, n_500, n_1000)
```
